import Head from 'next/head'
import {Inter} from 'next/font/google'
import {useSelector} from 'react-redux'

import {getItemsFromCategory, getMainCategories, getSubCategories} from "@/lib/categories";
import MainSection from "@/components/MainSection";
import CategoriesTab from "@/components/CategoriesTab";
import CategoriesList from "@/components/CategoriesList";
import {searchDatabaseByQuery} from "@/lib/notion";
import {useEffect, useState} from "react";

const inter = Inter({ subsets: ['latin'] })

export default function Home(props: any) {
    // const [categories, setCategories] = useState([]);
    // useEffect(() => {
    //     setCategories(props.categories);
    // }, [props.categories, categories])
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>
                <MainSection
                    categories={props.categories}
                />
                <CategoriesTab categories={props.categories} />
                {/*<CategoriesList categories={props.subCategories} />*/}
            </main>
        </>
  )
}

export async function getServerSideProps() {
    // TODO: черновик отрефачить и перенести в api
    // главные категории
    const categories = await getMainCategories();
    // подкатегории
    const subCategories = await getSubCategories(categories);
    // товарка
    const items = await getItemsFromCategory(subCategories);

    return {
        props: {
            categories: categories ?? [],
            subCategories: subCategories ?? [],
            items,
        },
    }
}
