import Head from 'next/head'
import {Inter} from 'next/font/google'

import {getMainCategories, getSubCategories} from "@/lib/categories";
import MainSection from "@/components/MainSection";
import Categories from "@/components/Categories";

const inter = Inter({ subsets: ['latin'] })

export default function Home({categories, subCategories}: any) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>
                <MainSection
                    categories={categories}
                />
                <Categories categories={categories} />
            </main>
        </>
  )
}

export async function getServerSideProps() {
    const categories = await getMainCategories();
    const subCategories = await getSubCategories();

    return {
        props: {
            categories: categories ?? [],
            subCategories: subCategories ?? [],
        },
    }
}
