import Head from 'next/head'
import {Inter} from 'next/font/google'

import {getMainCategories, getSubCategories} from "@/lib/categories";

const inter = Inter({ subsets: ['latin'] })

export default function Home({categories, subCategories}: any) {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
            </Head>
            <main>

            </main>
        </>
  )
}

export async function getServerSideProps(ctx) {
    const categories = await getMainCategories();
    const subCategories = await getSubCategories();

    return {
        props: {
            categories: categories ?? [],
            subCategories: subCategories ?? [],
        },
    }
}
